# ECOWAS Border Trade Intelligence and Analytics (Version 2)

## Impact Assessment of Regional Trade Diversion Following the AES Countries' Withdrawal from ECOWAS:
### A Data Analytics Case Study of the Tsamiya–Kamba Transit Corridor

---

## Project Background

Regional trade within West Africa depends heavily on efficient cross-border movement of goods, services, and people. Changes in regional political and economic relationships can alter established trade corridors, affecting customs operations, border infrastructure, security, and trade facilitation.

This project investigates a realistic hypothetical scenario in which regional trade routes are diverted following the withdrawal of Burkina Faso, Mali, and Niger (AES countries) from ECOWAS. The analysis focuses on the potential operational impact on the **Tsamiya–Kamba transit corridor** in Kebbi State, Nigeria, which serves as an alternative route connecting Benin and Niger.

---

## Problem Statement

Historically, a significant volume of cargo travelling from the Port of Cotonou (Benin) to Niger passed through the Malanville–Gaya border corridor.

In this hypothetical case study, changes in regional dynamics result in increased use of the Nigerian transit corridor through **Tsamiya** and **Kamba**, leading to:

- Increased border traffic.
- Longer vehicle queues.
- Increased customs workload.
- Changes in customs revenue.
- Increased processing time.
- Higher security risks.
- Greater pressure on existing border infrastructure.

Understanding these potential impacts is essential for strategic planning, efficient resource allocation, and evidence-based policy development.

---

## Project Objectives

This project aims to:

1. Simulate realistic cross-border trade transactions using synthetic data.
2. Measure changes in border traffic before and after the simulated trade diversion.
3. Assess the impact on customs revenue and trade value.
4. Evaluate changes in border processing efficiency.
5. Examine queue length and congestion patterns.
6. Assess changes in security incidents and smuggling risks.
7. Forecast future border traffic using machine learning techniques.
8. Present analytical findings through interactive dashboards and visualizations.

---

## Research Questions

The project seeks to answer the following questions:

- Which border posts experience the largest increase in traffic?
- How does increased traffic affect border processing time?
- Does congestion reduce operational efficiency?
- Which commodities contribute most to customs revenue?
- How are security incidents associated with increasing traffic?
- Can future border traffic be predicted using historical transaction data?

---

## Methodology

The project follows a complete end-to-end data analytics workflow:

1. Synthetic dataset generation.
2. Data cleaning and preprocessing.
3. Exploratory Data Analysis (EDA).
4. Statistical and business analysis.
5. SQL-based analytics.
6. Interactive Power BI dashboard development.
7. Machine learning and predictive modelling.
8. Streamlit web application development.
9. GitHub portfolio documentation.

---

## Important Note

**This project uses a carefully designed synthetic dataset created solely for educational, research, and portfolio purposes.**

The data do **not** represent official operational records of ECOWAS, the Nigeria Customs Service, the Nigerian Immigration Service, or any government institution. However, the simulated data are designed to reflect realistic border management scenarios and demonstrate practical applications of data analytics for regional trade and border operations.

---

## Expected Outcome

The outcome of this project is a practical analytical framework demonstrating how data analytics can support:

- Border management.
- Regional trade facilitation.
- Customs modernization.
- Operational planning.
- Infrastructure investment decisions.
- Security risk assessment.
- Evidence-based policy formulation within the ECOWAS region.

In [1]:
# ============================================================
# ECOWAS VERSION 2
# Trade Diversion Analytics
# Chapter 1 - Import Libraries
# ============================================================

import pandas as pd
import numpy as np
import random

from datetime import datetime, timedelta

random.seed(42)
np.random.seed(42)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# ============================================================
# Chapter 2 - Project Parameters
# ============================================================

N_RECORDS = 100000

START_DATE = datetime(2022, 1, 1)

END_DATE = datetime(2025, 12, 31)

TOTAL_DAYS = (END_DATE - START_DATE).days

DIVERSION_DATE = datetime(2024, 2, 1)

print("Project parameters created.")

Project parameters created.

In [3]:
# ============================================================
# Chapter 3 - Countries
# ============================================================

COUNTRIES = [

    "Nigeria",
    "Benin",
    "Niger",
    "Ghana",
    "Togo",
    "Burkina Faso",
    "Mali",
    "Cote d'Ivoire",
    "Senegal",
    "Guinea",
    "Liberia",
    "Sierra Leone",
    "Guinea-Bissau",
    "The Gambia",
    "Cape Verde"

]

print("Countries loaded:", len(COUNTRIES))

Countries loaded: 15

In [4]:
# ============================================================
# Chapter 4 - Border Posts
# ============================================================

BORDER_POSTS = {

    "Nigeria":[
        "Tsamiya",
        "Kamba",
        "Seme",
        "Illela",
        "Jibia"
    ],

    "Benin":[
        "Malanville",
        "Hillacondji"
    ],

    "Niger":[
        "Gaya",
        "Konni"
    ],

    "Ghana":[
        "Aflao",
        "Elubo",
        "Paga"
    ],

    "Togo":[
        "Kodjoviakope"
    ],

    "Burkina Faso":[
        "Cinkanse"
    ],

    "Mali":[
        "Gogui"
    ],

    "Cote d'Ivoire":[
        "Noe",
        "Pogo"
    ],

    "Senegal":[
        "Kidira"
    ],

    "Guinea":[
        "Kouremale"
    ],

    "Liberia":[
        "Bo Waterside"
    ],

    "Sierra Leone":[
        "Gbalamuya"
    ],

    "Guinea-Bissau":[
        "Sao Domingos"
    ],

    "The Gambia":[
        "Amdallai"
    ],

    "Cape Verde":[
        "Praia Port"
    ]

}

print("Border posts loaded.")

Border posts loaded.

In [5]:
# ============================================================
# Chapter 5 - Commodities
# ============================================================

COMMODITIES = [

    "Rice",
    "Vehicles",
    "Petroleum",
    "Livestock",
    "Textiles",
    "Electronics",
    "Pharmaceuticals",
    "Construction Materials",
    "Fertilizer",
    "Agricultural Produce"

]

print("Commodity list created.")

Commodity list created.

In [6]:
# ============================================================
# Chapter 6 - Generate Transaction Dates
# ============================================================

transaction_dates = []

for _ in range(N_RECORDS):

    random_days = random.randint(0, TOTAL_DAYS)

    transaction_dates.append(
        START_DATE + timedelta(days=random_days)
    )

print("Transaction dates generated:", len(transaction_dates))

Transaction dates generated: 100000

In [7]:
# ============================================================
# Chapter 7 - Before / After Diversion
# ============================================================

period = []

for date in transaction_dates:

    if date < DIVERSION_DATE:
        period.append("Before Diversion")
    else:
        period.append("After Diversion")

print(pd.Series(period).value_counts())

Before Diversion    51818
After Diversion     48182
Name: count, dtype: int64

In [8]:
# ============================================================
# Chapter 8 - Entry Country
# ============================================================

entry_country = []

before_weights = [

    0.12,   # Nigeria
    0.18,   # Benin
    0.12,   # Niger
    0.08,   # Ghana
    0.06,   # Togo
    0.06,   # Burkina Faso
    0.06,   # Mali
    0.06,   # Cote d'Ivoire
    0.05,   # Senegal
    0.05,   # Guinea
    0.04,   # Liberia
    0.04,   # Sierra Leone
    0.03,   # Guinea-Bissau
    0.03,   # The Gambia
    0.02    # Cape Verde

]

after_weights = [

    0.28,   # Nigeria ↑
    0.08,   # Benin ↓
    0.10,
    0.08,
    0.06,
    0.05,
    0.05,
    0.06,
    0.05,
    0.04,
    0.03,
    0.03,
    0.03,
    0.03,
    0.03

]

for p in period:

    if p == "Before Diversion":

        entry_country.append(
            random.choices(
                COUNTRIES,
                weights=before_weights,
                k=1
            )[0]
        )

    else:

        entry_country.append(
            random.choices(
                COUNTRIES,
                weights=after_weights,
                k=1
            )[0]
        )

print(pd.Series(entry_country).value_counts())

Nigeria          19734
Benin            13244
Niger            10774
Ghana             8031
Togo              6100
Cote d'Ivoire     5886
Burkina Faso      5504
Mali              5466
Senegal           5139
Guinea            4662
Liberia           3540
Sierra Leone      3468
The Gambia        3031
Guinea-Bissau     2970
Cape Verde        2451
Name: count, dtype: int64

In [9]:
# ============================================================
# Chapter 9 - Assign Border Posts
# ============================================================

border_post = []

for country, p in zip(entry_country, period):

    if country == "Nigeria":

        if p == "After Diversion":

            border_post.append(
                random.choices(
                    ["Tsamiya", "Kamba", "Seme", "Illela", "Jibia"],
                    weights=[0.40, 0.30, 0.12, 0.10, 0.08],
                    k=1
                )[0]
            )

        else:

            border_post.append(
                random.choices(
                    ["Tsamiya", "Kamba", "Seme", "Illela", "Jibia"],
                    weights=[0.15, 0.15, 0.30, 0.20, 0.20],
                    k=1
                )[0]
            )

    else:

        border_post.append(
            random.choice(BORDER_POSTS[country])
        )

print(pd.Series(border_post).value_counts())

Malanville      6633
Hillacondji     6611
Tsamiya         6395
Kodjoviakope    6100
Cinkanse        5504
Gogui           5466
Konni           5436
Gaya            5338
Kidira          5139
Kamba           4895
Kouremale       4662
Bo Waterside    3540
Seme            3520
Gbalamuya       3468
Amdallai        3031
Pogo            2988
Sao Domingos    2970
Noe             2898
Paga            2713
Elubo           2706
Illela          2636
Aflao           2612
Praia Port      2451
Jibia           2288
Name: count, dtype: int64

In [10]:
# ============================================================
# Chapter 10 - Transaction ID
# ============================================================

transaction_id = []

for i in range(1, N_RECORDS + 1):

    transaction_id.append(f"TRX{i:07d}")

print(transaction_id[:5])

['TRX0000001', 'TRX0000002', 'TRX0000003', 'TRX0000004', 'TRX0000005']

In [11]:
# ============================================================
# Chapter 11 - Origin Country
# ============================================================

origin_country = []

origin_weights = [
    0.08,   # Nigeria
    0.30,   # Benin
    0.05,   # Niger
    0.08,   # Ghana
    0.07,   # Togo
    0.05,   # Burkina Faso
    0.04,   # Mali
    0.12,   # Cote d'Ivoire
    0.05,   # Senegal
    0.05,   # Guinea
    0.03,   # Liberia
    0.03,   # Sierra Leone
    0.02,   # Guinea-Bissau
    0.02,   # The Gambia
    0.01    # Cape Verde
]

for _ in range(N_RECORDS):

    origin_country.append(
        random.choices(
            COUNTRIES,
            weights=origin_weights,
            k=1
        )[0]
    )

print(pd.Series(origin_country).value_counts())

Benin            30149
Cote d'Ivoire    11990
Nigeria           8059
Ghana             7968
Togo              7004
Guinea            5079
Burkina Faso      4993
Niger             4895
Senegal           4844
Mali              4043
Liberia           3050
Sierra Leone      2978
Guinea-Bissau     1989
The Gambia        1948
Cape Verde        1011
Name: count, dtype: int64

In [12]:
# ============================================================
# Chapter 12 - Destination Country
# ============================================================

destination_country = []

for p in period:

    if p == "After Diversion":

        destination_country.append(
            random.choices(
                ["Niger","Nigeria","Mali","Burkina Faso"],
                weights=[0.60,0.20,0.10,0.10],
                k=1
            )[0]
        )

    else:

        destination_country.append(
            random.choices(
                ["Nigeria","Niger","Mali","Burkina Faso"],
                weights=[0.40,0.35,0.15,0.10],
                k=1
            )[0]
        )

print(pd.Series(destination_country).value_counts())

Niger           47035
Nigeria         30308
Mali            12467
Burkina Faso    10190
Name: count, dtype: int64

In [13]:
# ============================================================
# Chapter 13 - Commodity
# ============================================================

commodity = []

before_weights = [
    0.15,
    0.10,
    0.10,
    0.10,
    0.10,
    0.10,
    0.10,
    0.10,
    0.05,
    0.10
]

after_weights = [
    0.18,
    0.08,
    0.18,
    0.08,
    0.08,
    0.10,
    0.08,
    0.12,
    0.05,
    0.05
]

for p in period:

    if p == "Before Diversion":

        commodity.append(
            random.choices(
                COMMODITIES,
                weights=before_weights,
                k=1
            )[0]
        )

    else:

        commodity.append(
            random.choices(
                COMMODITIES,
                weights=after_weights,
                k=1
            )[0]
        )

print(pd.Series(commodity).value_counts())

Rice                      16297
Petroleum                 13990
Construction Materials    10902
Electronics               10049
Vehicles                   9139
Textiles                   9087
Livestock                  9000
Pharmaceuticals            8900
Agricultural Produce       7663
Fertilizer                 4973
Name: count, dtype: int64

In [14]:
# ============================================================
# Chapter 14 - Vehicle Type
# ============================================================

vehicle_types = [

    "Heavy Truck",
    "Medium Truck",
    "Trailer",
    "Mini Truck",
    "Passenger Bus"

]

vehicle = []

vehicle_weights = [

    0.35,
    0.25,
    0.20,
    0.10,
    0.10

]

for _ in range(N_RECORDS):

    vehicle.append(
        random.choices(
            vehicle_types,
            weights=vehicle_weights,
            k=1
        )[0]
    )

print(pd.Series(vehicle).value_counts())

Heavy Truck      35032
Medium Truck     25061
Trailer          20072
Mini Truck       10011
Passenger Bus     9824
Name: count, dtype: int64

In [15]:
# ============================================================
# Chapter 15 - Trade Value
# ============================================================

trade_value = []

for v in vehicle:

    if v == "Trailer":

        value = np.random.normal(80000,15000)

    elif v == "Heavy Truck":

        value = np.random.normal(65000,12000)

    elif v == "Medium Truck":

        value = np.random.normal(45000,10000)

    elif v == "Mini Truck":

        value = np.random.normal(20000,5000)

    else:

        value = np.random.normal(12000,3000)

    trade_value.append(round(max(1000,value),2))

print("Trade values generated:", len(trade_value))

Trade values generated: 100000

In [16]:
# ============================================================
# Chapter 16 - Cargo Weight (kg)
# ============================================================

cargo_weight = []

for v in vehicle:

    if v == "Trailer":
        weight = np.random.normal(28000, 4000)

    elif v == "Heavy Truck":
        weight = np.random.normal(20000, 3000)

    elif v == "Medium Truck":
        weight = np.random.normal(12000, 2000)

    elif v == "Mini Truck":
        weight = np.random.normal(5000, 1000)

    else:
        weight = np.random.normal(800, 250)

    cargo_weight.append(round(max(100, weight), 2))

print("Cargo weights generated:", len(cargo_weight))

Cargo weights generated: 100000

In [17]:
# ============================================================
# Chapter 17 - Customs Duty
# ============================================================

customs_duty = []

for value in trade_value:

    rate = random.uniform(0.05, 0.20)

    duty = value * rate

    customs_duty.append(round(duty, 2))

print("Customs duty generated:", len(customs_duty))

Customs duty generated: 100000

In [18]:
# ============================================================
# Chapter 18 - Revenue Collected
# ============================================================

revenue = []

for duty in customs_duty:

    revenue_value = duty + np.random.normal(200, 100)

    revenue.append(round(max(0, revenue_value), 2))

print("Revenue generated:", len(revenue))

Revenue generated: 100000

In [19]:
# ============================================================
# Chapter 19 - Queue Length
# ============================================================

queue_length = []

for post, p in zip(border_post, period):

    if p == "After Diversion" and post in ["Tsamiya", "Kamba"]:

        queue = random.randint(40, 120)

    elif post in ["Seme", "Malanville"]:

        queue = random.randint(20, 70)

    else:

        queue = random.randint(5, 40)

    queue_length.append(queue)

print("Queue length generated:", len(queue_length))

Queue length generated: 100000

In [20]:
# ============================================================
# Chapter 20 - Processing Time
# ============================================================

processing_time = []

for queue_size in queue_length:

    time = 15 + (queue_size * 1.3) + np.random.normal(0, 8)

    processing_time.append(round(max(5, time), 1))

print("Processing time generated:", len(processing_time))

Processing time generated: 100000

In [21]:
# ============================================================
# Chapter 21 - Inspection Result
# ============================================================

inspection_result = []

for queue in queue_length:

    if queue > 80:

        result = random.choices(
            ["Passed", "Failed"],
            weights=[0.75, 0.25],
            k=1
        )[0]

    else:

        result = random.choices(
            ["Passed", "Failed"],
            weights=[0.92, 0.08],
            k=1
        )[0]

    inspection_result.append(result)

print(pd.Series(inspection_result).value_counts())

Passed    91159
Failed     8841
Name: count, dtype: int64

In [22]:
# ============================================================
# Chapter 22 - Smuggling Risk
# ============================================================

smuggling_risk = []

for commodity_name, value in zip(commodity, trade_value):

    if commodity_name in ["Petroleum", "Pharmaceuticals", "Electronics"] or value > 70000:

        risk = random.choices(
            ["Low", "Medium", "High"],
            weights=[0.20, 0.40, 0.40],
            k=1
        )[0]

    else:

        risk = random.choices(
            ["Low", "Medium", "High"],
            weights=[0.60, 0.30, 0.10],
            k=1
        )[0]

    smuggling_risk.append(risk)

print(pd.Series(smuggling_risk).value_counts())

Low       39460
Medium    35260
High      25280
Name: count, dtype: int64

In [23]:
# ============================================================
# Chapter 23 - Security Incident
# ============================================================

security_incident = []

for risk in smuggling_risk:

    if risk == "High":

        incident = random.choices(
            ["Yes", "No"],
            weights=[0.20, 0.80],
            k=1
        )[0]

    elif risk == "Medium":

        incident = random.choices(
            ["Yes", "No"],
            weights=[0.08, 0.92],
            k=1
        )[0]

    else:

        incident = random.choices(
            ["Yes", "No"],
            weights=[0.02, 0.98],
            k=1
        )[0]

    security_incident.append(incident)

print(pd.Series(security_incident).value_counts())

No     91309
Yes     8691
Name: count, dtype: int64

In [24]:
# ============================================================
# Chapter 24 - Border Efficiency Score
# ============================================================

efficiency_score = []

for queue_size, process in zip(queue_length, processing_time):

    score = 100

    score -= queue_size * 0.35

    score -= process * 0.20

    score += np.random.normal(0, 3)

    score = max(20, min(100, round(score, 1)))

    efficiency_score.append(score)

print("Efficiency scores generated:", len(efficiency_score))

Efficiency scores generated: 100000

In [25]:
# ============================================================
# Chapter 25 - Scanner Availability
# ============================================================

scanner_status = []

for post in border_post:

    if post in ["Tsamiya", "Kamba", "Seme", "Malanville"]:

        scanner_status.append(
            random.choices(
                ["Available", "Unavailable"],
                weights=[0.85, 0.15],
                k=1
            )[0]
        )

    else:

        scanner_status.append(
            random.choices(
                ["Available", "Unavailable"],
                weights=[0.60, 0.40],
                k=1
            )[0]
        )

print(pd.Series(scanner_status).value_counts())

Available      65371
Unavailable    34629
Name: count, dtype: int64

In [26]:
print(type(commodity))
print(len(commodity))

print(commodity[:10])

<class 'list'>
100000
['Vehicles', 'Livestock', 'Vehicles', 'Petroleum', 'Vehicles', 'Fertilizer', 'Rice', 'Pharmaceuticals', 'Rice', 'Construction Materials']

In [27]:
# ============================================================
# Chapter 26 - Create DataFrame
# ============================================================

df = pd.DataFrame({

    "Transaction_ID": transaction_id,
    "Transaction_Date": transaction_dates,
    "Period": period,

    "Origin_Country": origin_country,
    "Entry_Country": entry_country,
    "Destination_Country": destination_country,

    "Border_Post": border_post,

    "Commodity": commodity,
    "Vehicle_Type": vehicle,

    "Cargo_Weight_kg": cargo_weight,

    "Trade_Value_USD": trade_value,
    "Customs_Duty_USD": customs_duty,
    "Revenue_Collected_USD": revenue,

    "Queue_Length": queue_length,
    "Processing_Time_Minutes": processing_time,

    "Inspection_Result": inspection_result,

    "Smuggling_Risk": smuggling_risk,

    "Security_Incident": security_incident,

    "Scanner_Status": scanner_status,

    "Border_Efficiency_Score": efficiency_score

})

print(df.shape)

df.head()

(100000, 20)

,Transaction_ID,Transaction_Date,Period,Origin_Country,Entry_Country,Destination_Country,Border_Post,Commodity,Vehicle_Type,Cargo_Weight_kg,Trade_Value_USD,Customs_Duty_USD,Revenue_Collected_USD,Queue_Length,Processing_Time_Minutes,Inspection_Result,Smuggling_Risk,Security_Incident,Scanner_Status,Border_Efficiency_Score
0,TRX0000001,2025-08-02,After Diversion,Togo,Cape Verde,Niger,Praia Port,Vehicles,Heavy Truck,23091.78,70960.57,9435.26,9791.44,17,25.9,Passed,Medium,No,Unavailable,98.0
1,TRX0000002,2022-08-17,Before Diversion,Nigeria,Togo,Niger,Kodjoviakope,Livestock,Heavy Truck,16533.94,63340.83,11608.49,11799.07,22,48.0,Passed,Low,No,Unavailable,82.3
2,TRX0000003,2022-02-21,Before Diversion,Benin,Benin,Niger,Hillacondji,Vehicles,Passenger Bus,943.86,13943.07,2766.44,2833.49,25,46.5,Passed,Medium,No,Unavailable,76.8
3,TRX0000004,2023-07-18,Before Diversion,Benin,Sierra Leone,Nigeria,Gbalamuya,Petroleum,Heavy Truck,18142.28,83276.36,13714.69,13775.83,6,20.5,Passed,Medium,No,Available,95.3
4,TRX0000005,2023-05-17,Before Diversion,Benin,Mali,Nigeria,Gogui,Vehicles,Heavy Truck,19017.79,62190.16,10388.67,10554.40,26,54.9,Passed,Low,No,Available,79.7

In [28]:
print(df["Commodity"].head(10))

0                  Vehicles
1                 Livestock
2                  Vehicles
3                 Petroleum
4                  Vehicles
5                Fertilizer
6                      Rice
7           Pharmaceuticals
8                      Rice
9    Construction Materials
Name: Commodity, dtype: object

In [29]:
print(df["Commodity"].value_counts())

Commodity
Rice                      16297
Petroleum                 13990
Construction Materials    10902
Electronics               10049
Vehicles                   9139
Textiles                   9087
Livestock                  9000
Pharmaceuticals            8900
Agricultural Produce       7663
Fertilizer                 4973
Name: count, dtype: int64

In [30]:
# ============================================================
# Chapter 27 - Export CSV
# ============================================================

df.to_csv(
    "trade_diversion_transactions.csv",
    index=False
)

print("Dataset exported successfully!")

Dataset exported successfully!

In [31]:
# ============================================================
# Chapter 28 - Quality Check
# ============================================================

print(df.info())

print()

print(df.isnull().sum())

print()

print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Transaction_ID           100000 non-null  object
 1   Transaction_Date         100000 non-null  datetime64[ns]
 2   Period                   100000 non-null  object
 3   Origin_Country           100000 non-null  object
 4   Entry_Country            100000 non-null  object
 5   Destination_Country      100000 non-null  object
 6   Border_Post              100000 non-null  object
 7   Commodity                100000 non-null  object
 8   Vehicle_Type             100000 non-null  object
 9   Cargo_Weight_kg          100000 non-null  float64
 10  Trade_Value_USD          100000 non-null  float64
 11  Customs_Duty_USD         100000 non-null  float64
 12  Revenue_Collected_USD    100000 non-null  float64
 13  Queue_Length             100000 non-null  int64
 14  Processing_Time_Minutes  100000 non-null  float64
 15  Inspection_Result        100000 non-null  object
 16  Smuggling_Risk           100000 non-null  object
 17  Security_Incident        100000 non-null  object
 18  Scanner_Status           100000 non-null  object
 19  Border_Efficiency_Score  100000 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(12)
memory usage: 15.3+ MB
None

Transaction_ID             0
Transaction_Date           0
Period                     0
Origin_Country             0
Entry_Country              0
Destination_Country        0
Border_Post                0
Commodity                  0
Vehicle_Type               0
Cargo_Weight_kg            0
Trade_Value_USD            0
Customs_Duty_USD           0
Revenue_Collected_USD      0
Queue_Length               0
Processing_Time_Minutes    0
Inspection_Result          0
Smuggling_Risk             0
Security_Incident          0
Scanner_Status             0
Border_Efficiency_Score    0
dtype: int64

                 Transaction_Date  Cargo_Weight_kg  Trade_Value_USD  \
count                      100000    100000.000000    100000.000000
mean   2024-01-02 02:45:32.544000     16214.103278     53297.585829
min           2022-01-01 00:00:00       100.000000      1000.000000
25%           2022-12-31 00:00:00     10355.565000     36335.585000
50%           2024-01-04 12:00:00     16843.400000     55660.595000
75%           2025-01-03 00:00:00     22611.065000     71292.170000
max           2025-12-31 00:00:00     43907.470000    139134.970000
std                           NaN      8987.844739     24744.505959

       Customs_Duty_USD  Revenue_Collected_USD   Queue_Length  \
count     100000.000000          100000.000000  100000.000000
mean        6659.975868            6859.825048      30.246940
min           88.940000             195.960000       5.000000
25%         3451.275000            3649.927500      16.000000
50%         6121.890000            6317.740000      26.000000
75%         9288.057500            9485.842500      37.000000
max        26014.760000           26163.120000     120.000000
std         4001.657685            4003.413319      21.602791

       Processing_Time_Minutes  Border_Efficiency_Score
count            100000.000000            100000.000000
mean                 54.323805                78.528698
min                   5.000000                20.000000
25%                  35.200000                74.100000
50%                  49.150000                81.000000
75%                  64.100000                87.500000
max                 190.200000               100.000000
std                  29.189510                13.604477

trade_diversion_transactions# Border Posts Reference Dataset

This dataset contains the border posts included in the simulated ECOWAS trade diversion study.

It serves as a reference (dimension) table for analysis and visualization.

In [32]:
# ============================================================
# Chapter 28 - Export Border Posts
# ============================================================

border_posts = pd.DataFrame({

    "Border_Post": sorted(df["Border_Post"].unique())

})

border_posts.to_csv(
    "border_posts.csv",
    index=False
)

print("border_posts.csv exported successfully.")

border_posts

border_posts.csv exported successfully.

     Border_Post
0          Aflao
1       Amdallai
2   Bo Waterside
3       Cinkanse
4          Elubo
5           Gaya
6      Gbalamuya
7          Gogui
8    Hillacondji
9         Illela
10         Jibia
11         Kamba
12        Kidira
13  Kodjoviakope
14         Konni
15     Kouremale
16    Malanville
17           Noe
18          Paga
19          Pogo
20    Praia Port
21  Sao Domingos
22          Seme
23       Tsamiya

# Border Posts Reference Dataset

This dataset contains the border posts included in the simulated ECOWAS trade diversion study.

It serves as a reference (dimension) table for analysis and visualization.

In [33]:
# ============================================================
# Chapter 29 - Export Border Posts
# ============================================================

border_posts = pd.DataFrame({

    "Border_Post": sorted(df["Border_Post"].unique())

})

border_posts.to_csv(
    "border_posts.csv",
    index=False
)

print("border_posts.csv exported successfully.")

border_posts

border_posts.csv exported successfully.

     Border_Post
0          Aflao
1       Amdallai
2   Bo Waterside
3       Cinkanse
4          Elubo
5           Gaya
6      Gbalamuya
7          Gogui
8    Hillacondji
9         Illela
10         Jibia
11         Kamba
12        Kidira
13  Kodjoviakope
14         Konni
15     Kouremale
16    Malanville
17           Noe
18          Paga
19          Pogo
20    Praia Port
21  Sao Domingos
22          Seme
23       Tsamiya

# Regional Events Dataset

This dataset summarizes the simulated regional policy event that influenced the trade diversion scenario.

It provides contextual information for the analytical case study.

In [34]:
# ============================================================
# Chapter 29 - Export Regional Events
# ============================================================

regional_events = pd.DataFrame({

    "Event": [
        "AES Countries Withdrawal from ECOWAS"
    ],

    "Effective_Period": [
        "After Diversion"
    ],

    "Description": [
        "Simulated regional policy event used for ECOWAS border trade analytics."
    ]

})

regional_events.to_csv(
    "regional_events.csv",
    index=False
)

print("regional_events.csv exported successfully.")

regional_events

regional_events.csv exported successfully.

,Event,Effective_Period,Description
0,AES Countries Withdrawal from ECOWAS,After Diversion,Simulated regional policy event used for ECOWA...