# ECOWAS Border Trade Intelligence and Analytics

# SQL Analytics Using SQLite

## Impact Assessment of Simulated Regional Trade Diversion Following the AES Countries' Withdrawal from ECOWAS

### Case Study: Tsamiya–Kamba Transit Corridor

---

## Objective

This notebook demonstrates how SQL can be used to analyze border management data.

Using SQLite within Python, we answer common business questions related to customs revenue, border performance, trade flows, and operational efficiency.

The notebook highlights practical SQL skills frequently required in Data Analyst, Business Intelligence, and Data Science roles.

In [24]:
# ============================================================
# Chapter 1 - Import Libraries
# ============================================================

import pandas as pd
import sqlite3

print("Libraries imported successfully.")

Libraries imported successfully.

In [25]:
# ============================================================
# Chapter 2 - Load Dataset
# ============================================================

df = pd.read_csv("trade_diversion_transactions.csv")

print(df.shape)

df.head()

(100000, 20)

,Transaction_ID,Transaction_Date,Period,Origin_Country,Entry_Country,Destination_Country,Border_Post,Commodity,Vehicle_Type,Cargo_Weight_kg,Trade_Value_USD,Customs_Duty_USD,Revenue_Collected_USD,Queue_Length,Processing_Time_Minutes,Inspection_Result,Smuggling_Risk,Security_Incident,Scanner_Status,Border_Efficiency_Score
0,TRX0000001,2025-08-02,After Diversion,Togo,Cape Verde,Niger,Praia Port,Vehicles,Heavy Truck,23091.78,70960.57,9435.26,9791.44,17,25.9,Passed,Medium,No,Unavailable,98.0
1,TRX0000002,2022-08-17,Before Diversion,Nigeria,Togo,Niger,Kodjoviakope,Livestock,Heavy Truck,16533.94,63340.83,11608.49,11799.07,22,48.0,Passed,Low,No,Unavailable,82.3
2,TRX0000003,2022-02-21,Before Diversion,Benin,Benin,Niger,Hillacondji,Vehicles,Passenger Bus,943.86,13943.07,2766.44,2833.49,25,46.5,Passed,Medium,No,Unavailable,76.8
3,TRX0000004,2023-07-18,Before Diversion,Benin,Sierra Leone,Nigeria,Gbalamuya,Petroleum,Heavy Truck,18142.28,83276.36,13714.69,13775.83,6,20.5,Passed,Medium,No,Available,95.3
4,TRX0000005,2023-05-17,Before Diversion,Benin,Mali,Nigeria,Gogui,Vehicles,Heavy Truck,19017.79,62190.16,10388.67,10554.40,26,54.9,Passed,Low,No,Available,79.7

In [26]:
# ============================================================
# Chapter 3 - Create SQLite Database
# ============================================================

connection = sqlite3.connect("trade_diversion.db")

df.to_sql(
    "transactions",
    connection,
    if_exists="replace",
    index=False
)

print("Database created successfully.")

Database created successfully.

## SQL Query 1

Verify that the transaction table has been created successfully.

In [27]:
# ============================================================
# Chapter 4 - Show Tables
# ============================================================

query = """

SELECT name

FROM sqlite_master

WHERE type='table';

"""

tables = pd.read_sql(query, connection)

tables

           name
0  transactions

## SQL Query 2

Display the first ten transaction records.

In [28]:
# ============================================================
# Chapter 5 - Sample Records
# ============================================================

query = """

SELECT *

FROM transactions

LIMIT 10;

"""

pd.read_sql(query, connection)

,Transaction_ID,Transaction_Date,Period,Origin_Country,Entry_Country,Destination_Country,Border_Post,Commodity,Vehicle_Type,Cargo_Weight_kg,Trade_Value_USD,Customs_Duty_USD,Revenue_Collected_USD,Queue_Length,Processing_Time_Minutes,Inspection_Result,Smuggling_Risk,Security_Incident,Scanner_Status,Border_Efficiency_Score
0,TRX0000001,2025-08-02,After Diversion,Togo,Cape Verde,Niger,Praia Port,Vehicles,Heavy Truck,23091.78,70960.57,9435.26,9791.44,17,25.9,Passed,Medium,No,Unavailable,98.0
1,TRX0000002,2022-08-17,Before Diversion,Nigeria,Togo,Niger,Kodjoviakope,Livestock,Heavy Truck,16533.94,63340.83,11608.49,11799.07,22,48.0,Passed,Low,No,Unavailable,82.3
2,TRX0000003,2022-02-21,Before Diversion,Benin,Benin,Niger,Hillacondji,Vehicles,Passenger Bus,943.86,13943.07,2766.44,2833.49,25,46.5,Passed,Medium,No,Unavailable,76.8
3,TRX0000004,2023-07-18,Before Diversion,Benin,Sierra Leone,Nigeria,Gbalamuya,Petroleum,Heavy Truck,18142.28,83276.36,13714.69,13775.83,6,20.5,Passed,Medium,No,Available,95.3
4,TRX0000005,2023-05-17,Before Diversion,Benin,Mali,Nigeria,Gogui,Vehicles,Heavy Truck,19017.79,62190.16,10388.67,10554.40,26,54.9,Passed,Low,No,Available,79.7
5,TRX0000006,2023-04-03,Before Diversion,Cote d'Ivoire,Togo,Niger,Kodjoviakope,Fertilizer,Trailer,28190.42,76487.95,9790.49,9832.44,30,50.5,Failed,High,No,Unavailable,79.9
6,TRX0000007,2022-10-13,Before Diversion,Burkina Faso,Mali,Nigeria,Gogui,Rice,Passenger Bus,770.13,16737.64,2804.13,3062.84,22,47.3,Passed,Low,No,Available,83.3
7,TRX0000008,2022-07-29,Before Diversion,Mali,Benin,Mali,Hillacondji,Pharmaceuticals,Heavy Truck,14971.68,74209.22,13677.79,13897.61,30,50.1,Passed,Medium,No,Available,81.3
8,TRX0000009,2025-10-17,After Diversion,Cote d'Ivoire,Mali,Nigeria,Gogui,Rice,Trailer,33527.25,72957.88,8370.04,8574.99,29,54.7,Passed,High,Yes,Available,75.0
9,TRX0000010,2025-01-21,After Diversion,Benin,Burkina Faso,Nigeria,Cinkanse,Construction Materials,Trailer,32537.64,88138.40,16613.51,16751.57,32,50.2,Failed,High,No,Unavailable,81.9

## SQL Query 3

Determine the total number of border transactions.

In [29]:
# ============================================================
# Chapter 6 - Total Transactions
# ============================================================

query = """

SELECT COUNT(*) AS Total_Transactions

FROM transactions;

"""

pd.read_sql(query, connection)

   Total_Transactions
0              100000

## SQL Query 4

Identify the busiest border posts based on transaction volume.

In [30]:
# ============================================================
# Chapter 7 - Transactions by Border Post
# ============================================================

query = """

SELECT
    Border_Post,
    COUNT(*) AS Transactions

FROM transactions

GROUP BY Border_Post

ORDER BY Transactions DESC;

"""

pd.read_sql(query, connection)

     Border_Post  Transactions
0     Malanville          6633
1    Hillacondji          6611
2        Tsamiya          6395
3   Kodjoviakope          6100
4       Cinkanse          5504
5          Gogui          5466
6          Konni          5436
7           Gaya          5338
8         Kidira          5139
9          Kamba          4895
10     Kouremale          4662
11  Bo Waterside          3540
12          Seme          3520
13     Gbalamuya          3468
14      Amdallai          3031
15          Pogo          2988
16  Sao Domingos          2970
17           Noe          2898
18          Paga          2713
19         Elubo          2706
20        Illela          2636
21         Aflao          2612
22    Praia Port          2451
23         Jibia          2288

## SQL Query 5

This query identifies the border posts generating the highest customs revenue.

In [31]:
# ============================================================
# Chapter 8 - Revenue by Border Post
# ============================================================

query = """

SELECT
    Border_Post,
    ROUND(SUM(Revenue_Collected_USD),2) AS Total_Revenue

FROM transactions

GROUP BY Border_Post

ORDER BY Total_Revenue DESC;

"""

pd.read_sql(query, connection)

     Border_Post  Total_Revenue
0     Malanville    45736299.53
1    Hillacondji    45471352.72
2        Tsamiya    43904800.29
3   Kodjoviakope    42272743.73
4       Cinkanse    37720302.83
5           Gaya    37357217.26
6          Konni    37067911.70
7          Gogui    37039457.22
8         Kidira    35005284.17
9          Kamba    33655170.00
10     Kouremale    31856631.62
11  Bo Waterside    24217075.11
12     Gbalamuya    23821839.56
13          Seme    23695650.77
14      Amdallai    20662748.43
15          Pogo    20295565.32
16  Sao Domingos    20292146.36
17           Noe    20093601.73
18          Paga    18514492.85
19         Aflao    18425257.09
20        Illela    18387635.49
21         Elubo    18308650.53
22    Praia Port    16670672.17
23         Jibia    15509998.32

## SQL Query 6

This query ranks border posts according to their average queue length.

In [32]:
# ============================================================
# Chapter 9 - Average Queue Length
# ============================================================

query = """

SELECT
    Border_Post,
    ROUND(AVG(Queue_Length),2) AS Average_Queue

FROM transactions

GROUP BY Border_Post

ORDER BY Average_Queue DESC;

"""

pd.read_sql(query, connection)

     Border_Post  Average_Queue
0        Tsamiya          71.71
1          Kamba          69.27
2           Seme          45.17
3     Malanville          45.14
4      Gbalamuya          22.74
5   Bo Waterside          22.73
6          Elubo          22.70
7           Pogo          22.66
8    Hillacondji          22.61
9          Gogui          22.61
10  Kodjoviakope          22.60
11         Aflao          22.57
12      Cinkanse          22.55
13          Gaya          22.50
14          Paga          22.49
15         Konni          22.47
16  Sao Domingos          22.46
17    Praia Port          22.46
18         Jibia          22.46
19           Noe          22.38
20        Kidira          22.35
21     Kouremale          22.32
22      Amdallai          22.32
23        Illela          22.12

## SQL Query 7

This query identifies border posts with the longest average processing times.

In [33]:
# ============================================================
# Chapter 10 - Average Processing Time
# ============================================================

query = """

SELECT
    Border_Post,
    ROUND(AVG(Processing_Time_Minutes),2) AS Avg_Processing_Time

FROM transactions

GROUP BY Border_Post

ORDER BY Avg_Processing_Time DESC;

"""

pd.read_sql(query, connection)

     Border_Post  Avg_Processing_Time
0        Tsamiya               108.03
1          Kamba               105.14
2     Malanville                73.59
3           Seme                73.54
4   Bo Waterside                44.71
5      Gbalamuya                44.64
6           Pogo                44.58
7          Gogui                44.47
8    Hillacondji                44.44
9   Kodjoviakope                44.41
10         Jibia                44.35
11      Cinkanse                44.34
12         Aflao                44.31
13    Praia Port                44.29
14        Kidira                44.29
15         Elubo                44.27
16     Kouremale                44.25
17          Paga                44.17
18         Konni                44.16
19          Gaya                44.14
20  Sao Domingos                44.11
21           Noe                43.97
22      Amdallai                43.86
23        Illela                43.75

## SQL Query 8

This query ranks commodities by total customs revenue generated.

In [34]:
# ============================================================
# Chapter 11 - Revenue by Commodity
# ============================================================

query = """

SELECT
    Commodity,
    ROUND(SUM(Revenue_Collected_USD),2) AS Total_Revenue

FROM transactions

GROUP BY Commodity

ORDER BY Total_Revenue DESC;

"""

pd.read_sql(query, connection)

                Commodity  Total_Revenue
0                    Rice   1.109856e+08
1               Petroleum   9.575366e+07
2  Construction Materials   7.453293e+07
3             Electronics   6.930176e+07
4                Textiles   6.235231e+07
5                Vehicles   6.225603e+07
6               Livestock   6.220152e+07
7         Pharmaceuticals   6.107939e+07
8    Agricultural Produce   5.333761e+07
9              Fertilizer   3.418171e+07

## SQL Query 9

This query counts high-risk shipments for each commodity.

In [35]:
# ============================================================
# Chapter 12 - High-Risk Shipments
# ============================================================

query = """

SELECT
    Commodity,
    COUNT(*) AS High_Risk_Shipments

FROM transactions

WHERE Smuggling_Risk = 'High'

GROUP BY Commodity

ORDER BY High_Risk_Shipments DESC;

"""

pd.read_sql(query, connection)

                Commodity  High_Risk_Shipments
0               Petroleum                 5615
1             Electronics                 4061
2         Pharmaceuticals                 3516
3                    Rice                 2858
4  Construction Materials                 1991
5                Textiles                 1670
6               Livestock                 1643
7                Vehicles                 1620
8    Agricultural Produce                 1417
9              Fertilizer                  889

## SQL Query 10

This query summarizes customs revenue by month to identify revenue trends over time.

In [36]:
# ============================================================
# Chapter 13 - Monthly Revenue Trend
# ============================================================

query = """

SELECT
    strftime('%Y-%m', Transaction_Date) AS Month,
    ROUND(SUM(Revenue_Collected_USD),2) AS Revenue

FROM transactions

GROUP BY Month

ORDER BY Month;

"""

pd.read_sql(query, connection)

      Month      Revenue
0   2022-01  14692661.12
1   2022-02  13349102.20
2   2022-03  14389160.64
3   2022-04  14069010.90
4   2022-05  14487972.42
5   2022-06  14102169.56
6   2022-07  14980227.04
7   2022-08  14713512.37
8   2022-09  13429075.54
9   2022-10  15405272.33
10  2022-11  14169309.64
11  2022-12  14292907.94
12  2023-01  14927579.53
13  2023-02  12985731.36
14  2023-03  14091255.25
15  2023-04  14127018.44
16  2023-05  14267706.45
17  2023-06  13630714.62
18  2023-07  14392055.07
19  2023-08  14065092.83
20  2023-09  14040509.79
21  2023-10  14866056.14
22  2023-11  14031955.94
23  2023-12  13898231.19
24  2024-01  13957964.53
25  2024-02  13910164.82
26  2024-03  14836632.92
27  2024-04  14273756.60
28  2024-05  14557175.23
29  2024-06  14682844.45
30  2024-07  14773658.01
31  2024-08  14698791.04
32  2024-09  14111716.41
33  2024-10  14942372.04
34  2024-11  13834282.82
35  2024-12  13895369.59
36  2025-01  13828828.72
37  2025-02  13125154.07
38  2025-03  14665892.43
39  2025-04  13701401.45
40  2025-05  14606962.65
41  2025-06  14034911.60
42  2025-07  14956430.77
43  2025-08  14862035.15
44  2025-09  14741513.41
45  2025-10  14315922.17
46  2025-11  15160149.80
47  2025-12  14104285.81

## SQL Query 11

This query identifies border posts with the highest number of reported security incidents.

In [37]:
# ============================================================
# Chapter 14 - Security Incidents
# ============================================================

query = """

SELECT
    Border_Post,
    COUNT(*) AS Security_Incidents

FROM transactions

WHERE Security_Incident = 'Yes'

GROUP BY Border_Post

ORDER BY Security_Incidents DESC;

"""

pd.read_sql(query, connection)

     Border_Post  Security_Incidents
0     Malanville                 580
1    Hillacondji                 549
2        Tsamiya                 547
3   Kodjoviakope                 524
4       Cinkanse                 498
5           Gaya                 485
6          Konni                 468
7          Gogui                 465
8         Kidira                 458
9          Kamba                 432
10     Kouremale                 414
11          Seme                 314
12  Bo Waterside                 301
13     Gbalamuya                 286
14      Amdallai                 252
15           Noe                 251
16  Sao Domingos                 249
17          Pogo                 245
18        Illela                 244
19         Elubo                 241
20    Praia Port                 235
21         Aflao                 234
22          Paga                 223
23         Jibia                 196

## SQL Query 12

This query uses a SQL window function to rank border posts based on total customs revenue.

In [38]:
# ============================================================
# Chapter 15 - Revenue Ranking
# ============================================================

query = """

SELECT
    Border_Post,
    ROUND(SUM(Revenue_Collected_USD),2) AS Total_Revenue,

    RANK() OVER(
        ORDER BY SUM(Revenue_Collected_USD) DESC
    ) AS Revenue_Rank

FROM transactions

GROUP BY Border_Post;

"""

pd.read_sql(query, connection)

     Border_Post  Total_Revenue  Revenue_Rank
0     Malanville    45736299.53             1
1    Hillacondji    45471352.72             2
2        Tsamiya    43904800.29             3
3   Kodjoviakope    42272743.73             4
4       Cinkanse    37720302.83             5
5           Gaya    37357217.26             6
6          Konni    37067911.70             7
7          Gogui    37039457.22             8
8         Kidira    35005284.17             9
9          Kamba    33655170.00            10
10     Kouremale    31856631.62            11
11  Bo Waterside    24217075.11            12
12     Gbalamuya    23821839.56            13
13          Seme    23695650.77            14
14      Amdallai    20662748.43            15
15          Pogo    20295565.32            16
16  Sao Domingos    20292146.36            17
17           Noe    20093601.73            18
18          Paga    18514492.85            19
19         Aflao    18425257.09            20
20        Illela    18387635.49            21
21         Elubo    18308650.53            22
22    Praia Port    16670672.17            23
23         Jibia    15509998.32            24

## SQL Query 13

This query ranks commodities according to their total trade value.

In [39]:
# ============================================================
# Chapter 16 - Commodity Ranking
# ============================================================

query = """

SELECT
    Commodity,

    ROUND(SUM(Trade_Value_USD),2) AS Trade_Value,

    DENSE_RANK() OVER(
        ORDER BY SUM(Trade_Value_USD) DESC
    ) AS Commodity_Rank

FROM transactions

GROUP BY Commodity;

"""

pd.read_sql(query, connection)

                Commodity   Trade_Value  Commodity_Rank
0                    Rice  8.650819e+08               1
1               Petroleum  7.418711e+08               2
2  Construction Materials  5.823168e+08               3
3             Electronics  5.371690e+08               4
4                Vehicles  4.843910e+08               5
5                Textiles  4.841460e+08               6
6               Livestock  4.813193e+08               7
7         Pharmaceuticals  4.743106e+08               8
8    Agricultural Produce  4.130169e+08               9
9              Fertilizer  2.661360e+08              10

## SQL Query 14

This query demonstrates the use of a Common Table Expression (CTE) to identify border posts with above-average customs revenue.

In [40]:
# ============================================================
# Chapter 17 - CTE Example
# ============================================================

query = """

WITH RevenueSummary AS (

    SELECT
        Border_Post,
        SUM(Revenue_Collected_USD) AS Revenue

    FROM transactions

    GROUP BY Border_Post

)

SELECT *

FROM RevenueSummary

WHERE Revenue >

(
    SELECT AVG(Revenue)

    FROM RevenueSummary
);

"""

pd.read_sql(query, connection)

     Border_Post      Revenue
0       Cinkanse  37720302.83
1           Gaya  37357217.26
2          Gogui  37039457.22
3    Hillacondji  45471352.72
4          Kamba  33655170.00
5         Kidira  35005284.17
6   Kodjoviakope  42272743.73
7          Konni  37067911.70
8      Kouremale  31856631.62
9     Malanville  45736299.53
10       Tsamiya  43904800.29

## SQL Query 15

A SQL View stores a reusable query for future analysis.

In [41]:
# ============================================================
# Chapter 18 - Create SQL View
# ============================================================

query = """

CREATE VIEW IF NOT EXISTS BorderRevenue AS

SELECT

    Border_Post,

    ROUND(SUM(Revenue_Collected_USD),2) AS Revenue

FROM transactions

GROUP BY Border_Post;

"""

connection.execute(query)

print("SQL View created successfully.")

SQL View created successfully.

## SQL Query 16

Retrieve data from the SQL View created previously.

In [42]:
# ============================================================
# Chapter 19 - Query SQL View
# ============================================================

query = """

SELECT *

FROM BorderRevenue

ORDER BY Revenue DESC;

"""

pd.read_sql(query, connection)

     Border_Post      Revenue
0     Malanville  45736299.53
1    Hillacondji  45471352.72
2        Tsamiya  43904800.29
3   Kodjoviakope  42272743.73
4       Cinkanse  37720302.83
5           Gaya  37357217.26
6          Konni  37067911.70
7          Gogui  37039457.22
8         Kidira  35005284.17
9          Kamba  33655170.00
10     Kouremale  31856631.62
11  Bo Waterside  24217075.11
12     Gbalamuya  23821839.56
13          Seme  23695650.77
14      Amdallai  20662748.43
15          Pogo  20295565.32
16  Sao Domingos  20292146.36
17           Noe  20093601.73
18          Paga  18514492.85
19         Aflao  18425257.09
20        Illela  18387635.49
21         Elubo  18308650.53
22    Praia Port  16670672.17
23         Jibia  15509998.32

## SQL Query 17

Identify the five border posts with the highest average operational efficiency.

In [43]:
# ============================================================
# Chapter 20 - Efficiency Ranking
# ============================================================

query = """

SELECT

    Border_Post,

    ROUND(AVG(Border_Efficiency_Score),2) AS Avg_Efficiency

FROM transactions

GROUP BY Border_Post

ORDER BY Avg_Efficiency DESC

LIMIT 5;

"""

pd.read_sql(query, connection)

    Border_Post  Avg_Efficiency
0        Illela           83.56
1  Sao Domingos           83.40
2           Noe           83.37
3      Amdallai           83.34
4          Paga           83.33

## Export SQL Results

Export selected SQL query outputs for reporting and visualization.

In [44]:
# ============================================================
# Chapter 21 - Export SQL Results
# ============================================================

border_revenue = pd.read_sql("""

SELECT
    Border_Post,
    ROUND(SUM(Revenue_Collected_USD),2) AS Revenue

FROM transactions

GROUP BY Border_Post

ORDER BY Revenue DESC;

""", connection)

border_revenue.to_csv(
    "sql_border_revenue.csv",
    index=False
)

print("SQL results exported successfully.")

SQL results exported successfully.

In [45]:
# ============================================================
# Chapter 22 - Close Connection
# ============================================================

connection.close()

print("SQLite connection closed.")

SQLite connection closed.